name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: cache-pnpm-${{ hashFiles('./pnpn-lock.yaml') }}
          restore-keys: cache-pnpm-

      - name: Install dependencies
        run: corepack enable && corepack prepare pnpm@latest --activate && pnpm i

      - name: Build project
        run: pnpm prod
        env:
          REPO_NAME: ${{ github.event.repository.name }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: '${{ env.PATH_TO_DIST }}'
          branch: gh-pages
          single-commit: true
